# Generated by Django 5.2 on 2025-04-23 12:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(max_length=300, verbose_name='Описание')),
                ('reason', models.CharField(choices=[('birthday', 'День рождения'), ('wedding', 'Свадьба'), ('charity', 'Благотворительность'), ('other', 'Другое')], max_length=20, verbose_name='Повод')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения сбора')),
                ('target', models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для бесконечного сбора', null=True, verbose_name='Цель сбора')),
                ('image', models.ImageField(blank=True, null=True, upload_to='collects/images/', verbose_name='Обложка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000000000)], verbose_name='Сумма платежа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
