# Generated by Django 5.2 on 2025-04-24 06:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collects', '0002_alter_collect_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collect',
            name='target',
            field=models.PositiveIntegerField(blank=True, help_text='Оставьте пустым для бесконечного сбора', null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(2000000000)], verbose_name='Цель сбора'),
        ),
    ]
